
[package]
name = "rust_counter"
version = "0.1.0"
authors = ["chris"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysfs_gpio = "0.5"
rumq-client = "0.1.0-alpha.10"
tokio = "0.2.0-alpha.6"


